version: '3.4'

services:
  notificationservice:
    image: ${DOCKER_REGISTRY-}notificationservice
    build:
      context: .
      dockerfile: NotificationService/Dockerfile

  api-gateway:
    image: ${DOCKER_REGISTRY-}api-gateway
    build:
        context: .
        dockerfile: API.Gateway/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
        context: .
        dockerfile: IdentityServer/Dockerfile

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
        context: .
        dockerfile: UserService/Dockerfile

  jobservice:
    image: ${DOCKER_REGISTRY-}jobservice
    build:
        context: .
        dockerfile: JobService/Dockerfile

