version: '3.4'

services:
    apigateway:
        image: ${DOCKER_REGISTRY-}apigateway
        container_name: ApiGateway
        build:
          context: .
          dockerfile: API.Gateway/Dockerfile

    identityserver:
        image: ${DOCKER_REGISTRY-}identityserver
        container_name: IdentityServer
        build:
          context: .
          dockerfile: IdentityServer/Dockerfile

    userservice:
        image: ${DOCKER_REGISTRY-}userservice
        container_name: UserService
        build:
          context: .
          dockerfile: UserService/Dockerfile

    jobservice:
        image: ${DOCKER_REGISTRY-}jobservice
        container_name: JobService
        build:
          context: .
          dockerfile: JobService/Dockerfile

    notificationservice:
        image: ${DOCKER_REGISTRY-}notificationservice
        container_name: NotificationService
        build:
          context: .
          dockerfile: NotificationService/Dockerfile
